'''Observability sink interface used by the execution plane.'''

from __future__ import annotations

from typing import Any, Mapping, Protocol, runtime_checkable

from .types import SpanRef


@runtime_checkable
class EventSink(Protocol):
    '''Execution-plane observability interface.'''

    def run_started(self, run_id: int, message: str | None = None, payload: Mapping[str, Any] | None = None) -> Any: ...
    def run_completed(self, run_id: int, message: str | None = None, payload: Mapping[str, Any] | None = None) -> Any: ...
    def run_failed(self, run_id: int, error_message: str, payload: Mapping[str, Any] | None = None) -> Any: ...
    def run_cancelled(self, run_id: int, message: str | None = None, payload: Mapping[str, Any] | None = None) -> Any: ...

    def semantic_event(
        self,
        run_id: int,
        name: str,
        message: str | None = None,
        payload: Mapping[str, Any] | None = None,
        level: str = 'info',
        parent_span: SpanRef | None = None,
        node_name: str | None = None,
    ) -> Any: ...

    def span_started(
        self,
        run_id: int,
        span_type: str,
        name: str,
        node_name: str | None = None,
        parent: SpanRef | None = None,
        metadata: Mapping[str, Any] | None = None,
    ) -> SpanRef: ...
    def span_completed(self, span: SpanRef, output_summary: str | None = None, metrics: Mapping[str, Any] | None = None, metadata: Mapping[str, Any] | None = None) -> Any: ...
    def span_failed(self, span: SpanRef, error_message: str, metrics: Mapping[str, Any] | None = None, metadata: Mapping[str, Any] | None = None) -> Any: ...

    def node_started(self, run_id: int, node_name: str, attempt: int = 1, parent: SpanRef | None = None) -> SpanRef: ...
    def node_completed(self, span: SpanRef, output_summary: str | None = None, metrics: Mapping[str, Any] | None = None) -> Any: ...
    def node_failed(self, span: SpanRef, error_message: str, metrics: Mapping[str, Any] | None = None) -> Any: ...

    def llm_started(self, run_id: int, name: str, node_name: str | None = None, parent: SpanRef | None = None, provider: str | None = None, model: str | None = None) -> SpanRef: ...
    def llm_completed(self, span: SpanRef, output_summary: str | None = None, metrics: Mapping[str, Any] | None = None) -> Any: ...
    def llm_failed(self, span: SpanRef, error_message: str, metrics: Mapping[str, Any] | None = None) -> Any: ...

    def tool_started(self, run_id: int, tool_name: str, node_name: str | None = None, parent: SpanRef | None = None) -> SpanRef: ...
    def tool_completed(self, span: SpanRef, output_summary: str | None = None, metrics: Mapping[str, Any] | None = None) -> Any: ...
    def tool_failed(self, span: SpanRef, error_message: str, metrics: Mapping[str, Any] | None = None) -> Any: ...

    def artifact_created(self, run_id: int, storage_key: str, name: str, kind: str, span: SpanRef | None = None, metadata: Mapping[str, Any] | None = None) -> Any: ...
    def checkpoint_saved(self, run_id: int, thread_id: str, checkpoint_id: str, backend: str, span: SpanRef | None = None, state_summary: str | None = None) -> Any: ...
