# Generated by Django 6.0.7 on 2026-07-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_execution_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('truncation_reason', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_payloads', to='automation.run')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='auto_diag_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_id', 'field_name'), name='unique_diagnostic_target_field')],
            },
        ),
    ]
