# Generated by Django 6.0.7 on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("automation", "0006_diagnostic_payload")]

    operations = [
        migrations.CreateModel(
            name="IntegrationProjectionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("integration_id", models.CharField(db_index=True, max_length=100)),
                ("schema_id", models.CharField(db_index=True, max_length=200)),
                ("owner_kind", models.CharField(choices=[("run", "Run"), ("execution_unit", "Execution unit"), ("interaction", "Interaction"), ("artifact", "Artifact"), ("checkpoint", "Checkpoint")], default="run", max_length=32)),
                ("owner_external_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("truncated", models.BooleanField(default=False)),
                ("truncation_reason", models.CharField(blank=True, default="", max_length=64)),
                ("retention_class", models.CharField(default="execution_detail", max_length=64)),
                ("classification", models.CharField(default="internal", max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="integration_projections", to="automation.run")),
                ("span", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="integration_projections", to="automation.executionspan")),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["run", "integration_id"], name="auto_proj_run_int_idx"),
                    models.Index(fields=["span", "schema_id"], name="auto_proj_span_schema_idx"),
                    models.Index(fields=["run", "owner_kind"], name="auto_proj_run_owner_idx"),
                ],
            },
        )
    ]
