# Generated by Django 6.0.7 on 2026-07-24

from django.db import migrations, models
import django.utils.timezone


def backfill_projection_semantics(apps, schema_editor):
    Record = apps.get_model("automation", "IntegrationProjectionRecord")
    for record in Record.objects.all().iterator():
        payload = record.payload if isinstance(record.payload, dict) else {}
        schema_id = record.schema_id or ""
        projection_kind = "event"
        subject_kind = record.owner_kind or "run"
        subject_external_id = record.owner_external_id or ""
        if schema_id in {"langgraph.task.v1", "llamaindex.step.v1"}:
            projection_kind = "snapshot"
            subject_kind = "execution_unit"
            subject_external_id = str(
                payload.get("node_name") or payload.get("step_name") or subject_external_id
            )
        elif schema_id == "langgraph.interrupt.v1":
            projection_kind = "snapshot"
            subject_kind = "interaction"
            subject_external_id = str(payload.get("interrupt_id") or subject_external_id)
        elif schema_id == "langgraph.checkpoint_ref.v1":
            projection_kind = "reference"
            subject_kind = "checkpoint"
            checkpoint = payload.get("checkpoint")
            if isinstance(checkpoint, dict):
                subject_external_id = str(
                    checkpoint.get("checkpoint_id") or subject_external_id
                )
        elif schema_id == "integration.actions.v1":
            projection_kind = "action"
            subject_kind = "action"
            subject_external_id = "resume"
        record.projection_kind = projection_kind
        record.subject_kind = subject_kind
        record.subject_external_id = subject_external_id
        record.sequence = record.pk or 0
        record.occurred_at = record.created_at or django.utils.timezone.now()
        record.save(
            update_fields=[
                "projection_kind",
                "subject_kind",
                "subject_external_id",
                "sequence",
                "occurred_at",
            ]
        )



class Migration(migrations.Migration):
    dependencies = [("automation", "0007_integration_projection")]
    operations = [
        migrations.AddField(model_name="integrationprojectionrecord", name="projection_kind", field=models.CharField(choices=[("snapshot", "Snapshot"), ("event", "Event"), ("reference", "Reference"), ("action", "Action")], db_index=True, default="event", max_length=32)),
        migrations.AddField(model_name="integrationprojectionrecord", name="subject_kind", field=models.CharField(choices=[("run", "Run"), ("execution_unit", "Execution unit"), ("interaction", "Interaction"), ("artifact", "Artifact"), ("checkpoint", "Checkpoint"), ("action", "Action")], db_index=True, default="run", max_length=32)),
        migrations.AddField(model_name="integrationprojectionrecord", name="subject_external_id", field=models.CharField(blank=True, default="", max_length=255)),
        migrations.AddField(model_name="integrationprojectionrecord", name="sequence", field=models.PositiveBigIntegerField(default=0)),
        migrations.AddField(model_name="integrationprojectionrecord", name="occurred_at", field=models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
        migrations.RunPython(backfill_projection_semantics, migrations.RunPython.noop),
        migrations.AddIndex(model_name="integrationprojectionrecord", index=models.Index(fields=["run", "projection_kind"], name="auto_proj_run_kind_idx")),
        migrations.AddIndex(model_name="integrationprojectionrecord", index=models.Index(fields=["run", "subject_kind", "subject_external_id"], name="auto_proj_subject_idx")),
        migrations.AlterModelOptions(name="integrationprojectionrecord", options={"ordering": ["occurred_at", "sequence", "created_at"]}),
    ]
